// <auto-generated />
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("PrimeMath")]
[assembly: AssemblyDescription("")]
[assembly: Guid("a524cdcb-19ca-4d30-992d-49d0e66a1ca9")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CLSCompliant(true)]
