// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("PrimeMath.Tests")]
[assembly: AssemblyDescription("")]
[assembly: Guid("98bc58ad-0e3c-4659-b83c-004322757c6a")]
